#!/bin/bash
VER=`grep version cmd/indexer/main.go | grep -Po '[\d.]+'`
FILE=indexer-$VER.exe
GOOS=windows
GOARCH=386
CGO_ENABLED=1
CC=i686-w64-mingw32-gcc

env CC=$CC GOOS=$GOOS GOARCH=$GOARCH CGO_ENABLED=$CGO_ENABLED go build -gccgoflags "-g -O2 -m32" -ldflags "-w -s" -x -o bin/win32/$FILE ./cmd/indexer

if [ -f bin/win32/$FILE ]; then
	upx -6 bin/win32/$FILE
else
	echo 'не найден файл ${FILE}'
fi
